services:
  fodderly-app-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: fodderlydocker/fodderly-dev-web:1.0.29
    container_name: fodderly-dev-web
    ports:
      - ${APP_PORT:-3000}:80
    restart: always
    labels:
      project: "fodderly-app-web"
 